# Multiples of 3 or 5
# Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#
# Answer:  4613732
# Completed on Wed, 13 Jan 2016, 11:46


# By giving 2 sequences, it will return a list of last two items
def next_sequences(a, b):
    if a+b < 4000000:
        return [b, a+b]
    
    # it's bigger than the question expected value
    return False


# Fibonacci starting sequences
w = [1,1]
result = 0
while w :=  next_sequences(w[0], w[1]):
    # Check if last sequence is even
    if w[1]%2 == 0:
        # Sum last even value by result
        result += w[1]


print(result)